version: 2

# Circle jobs
jobs:

  # Publish the image set to S3
  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Initialise submodules
          command: git submodule init && git submodule update --remote
      - run:
          name: Publish to EU bucket
          command: ./node_modules/.bin/oist publish-s3 --bucket origami-imageset-data-eu --scheme ${IMAGESET_SCHEME} --source-directory=${IMAGESET_SOURCE_DIRECTORY} --scheme-version $CIRCLE_TAG
      - run:
          name: Publish to US bucket
          command: ./node_modules/.bin/oist publish-s3 --bucket origami-imageset-data-us --scheme ${IMAGESET_SCHEME} --source-directory=${IMAGESET_SOURCE_DIRECTORY} --scheme-version $CIRCLE_TAG
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run: npm version --git-tag-version=false ${CIRCLE_TAG}
      - run: npm publish --access=public

# Circle workflows
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
